# Generated by Django 5.2.8 on 2025-11-26 02:49

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boutique',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Boutique', 'verbose_name_plural': 'Boutiques'},
        ),
        migrations.AlterField(
            model_name='boutique',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image de la boutique'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom de la boutique'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='prestataire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to='core.prestataire', verbose_name='Prestataire'),
        ),
    ]
