# Generated by Django 5.2.8 on 2025-11-20 21:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_service_image_alter_service_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
