# Generated by Django 5.2.8 on 2025-11-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_boutique_options_alter_boutique_date_creation_and_more'),
    ]

    operations = [
    ]
