# Generated by Django 5.2.8 on 2025-11-26 03:00

from django.db import migrations, models
import cloudinary.models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_boutique_options_alter_boutique_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de la boutique")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date de création")),
                ('image', cloudinary.models.CloudinaryField(blank=True, null=True, verbose_name="Image de la boutique")),
                ('prestataire', models.OneToOneField(
                    on_delete=models.CASCADE,
                    related_name='boutique',
                    to='core.prestataire',
                    verbose_name="Prestataire"
                )),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ['-date_creation'],
            },
        ),
    ]
