# Generated by Django 5.2.8 on 2025-11-21 09:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_profil'),
        ),
    ]
