# Generated by Django 5.2.8 on 2025-11-30 22:23

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recreate_boutique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boutique',
            options={},
        ),
        migrations.AlterField(
            model_name='boutique',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_boutique'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='prestataire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to='core.prestataire'),
        ),
    ]
