# Generated by Django 5.2.8 on 2025-11-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ville',
            field=models.CharField(choices=[('Abidjan', 'Abidjan'), ('Bouaké', 'Bouaké'), ('Daloa', 'Daloa'), ('Yamoussoukro', 'Yamoussoukro'), ('San-Pédro', 'San-Pédro'), ('Korhogo', 'Korhogo'), ('Man', 'Man'), ('Gagnoa', 'Gagnoa')], default='Abidjan', max_length=50),
        ),
    ]
