# Generated by Django 5.2.8 on 2025-12-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_boutique_options_alter_boutique_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='categorie',
            field=models.CharField(choices=[('emploi', "Boutique d'offres d'emploi"), ('vente', 'Boutique de vente')], default='emploi', max_length=20),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boutique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boutiques/'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='prestataire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.prestataire'),
        ),
    ]
