# Generated by Django 5.2.8 on 2025-12-01 18:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_boutique_categorie_alter_boutique_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_boutique'),
        ),
    ]
