# Generated by Django 5.2.8 on 2025-11-23 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_avis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='email',
        ),
    ]
