# Generated by Django 5.2.8 on 2025-12-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_boutique_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='categorie',
            field=models.CharField(choices=[('emploi', "Boutique d'emploi"), ('vente', 'Boutique de vente')], default='emploi', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
