# Generated by Django 5.2.8 on 2025-11-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_avis_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
