# Generated by Django 5.2.8 on 2025-12-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_conversationmessage_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='type_utilisateur',
            field=models.CharField(choices=[('prestataire', 'Prestataire'), ('demandeur', 'Demandeur')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
