# Generated by Django 5.2.8 on 2025-12-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_abonnement_type_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='note_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='preuve_paiement',
            field=models.FileField(blank=True, null=True, upload_to='preuves_abonnement/'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='type_utilisateur',
            field=models.CharField(choices=[('prestataire', 'Prestataire')], default='prestataire', max_length=20),
        ),
    ]
