# Generated by Django 5.2.8 on 2025-12-11 17:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_abonnement_note_admin_abonnement_preuve_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='preuve_paiement',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='preuve de paiement'),
        ),
    ]
