# Generated by Django 5.2.8 on 2026-02-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_abonnement_preuve_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avis_plateforme',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('ami', 'Recommandation d’un ami'), ('ecole', 'École / Université'), ('tiktok', 'TikTok'), ('autre', 'Autre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
