# Generated by Django 5.2.8 on 2026-02-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_avis_plateforme_user_source_user_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='est_recent',
            field=models.BooleanField(default=False, help_text='Cocher pour forcer ce service comme récent'),
        ),
    ]
